export const MENU_BREAK_POINT = 968;
export const PAGE_SIZE = 10;
export const SELECT_PAGE_SIZE = 100;
export const PAGE_OPTIONS = [10, 20, 50, 100];
export const ROLE_USER = 1;
export const ROLE_MANAGER = 2;
export const ROLE_ADMIN = 3;
export const UNVERIFIED_USER = 0;
export const VERIFIED_USER = 1;
