// User reducer types
export const SET_REFRESHING = 'SET_REFRESHING';
export const STOP_REFRESHING = 'STOP_REFRESING';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const STOP_LOADING_USER = 'STOP_LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const LOADING_DASHBOARD_UI = 'LOADING_DASHBOARD_UI';
export const STOP_LOADING_DASHBOARD_UI = 'STOP_LOADING_DASHBOARD_UI';
